version: '2'

services:
  grafana:
    image: grafana/grafana:7.3.5
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=stablenet-datasource
    ports:
      - 3000:3000
    volumes:
      - ./grafana-plugins:/var/lib/grafana/plugins
